version: '3.1'
services:
  stats-server:
    build: ./stats-server/service
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats_db
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=aDd1m7in@
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
      - STATS_SERVER_URL=http://localhost:9090

  stats-db:
    image: postgres:13.7-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=aDd1m7in@

  ewm-service:
    build: ./ewm-service
    image: ewm-service-image
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=a@d1m0iPn
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
      - EWM_SERVICE_URL=http://localhost:8080

  ewm-db:
    image: postgres:13.7-alpine
    container_name: ewm-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=a@d1m0iPn
